### PR TITLE
Add friendly names and descriptions for segments

### PR DESCRIPTION
**Pull request by tdsmith**
Is there a good place to link people for more context on the segments? I was working from DTMO, which seemed kinda sparse.

### CODE REVIEW

**Review by felixlawrence — APPROVED** [review]
Might be worth linking to each segment definition in each `description`? E.g. linking to https://docs.telemetry.mozilla.org/concepts/segments.html#regular-users-v3

Would love to hear specific pain points/requests for improvements for the docs.

**Comment by tdsmith** [comment]
The DTMO copy describes them well but is there a good reference that talks about, like, how these were produced and why they're meaningful?

**Comment by felixlawrence** [comment]
> The DTMO copy describes them well but is there a good reference that talks about, like, how these were produced and why they're meaningful?

Ah, most of that info is buried in the PRs and links in the PRs. E.g. [regular users v3](https://github.com/mozilla/firefox-data-docs/pull/466), [weekday/all-week regulars](https://github.com/mozilla/firefox-data-docs/pull/493). I thought "how these were produced" is mostly of historical interest. "Why they're meaningful" is going to be different in different contexts - e.g. for experiments, separating "new or resurrected v3" lets us (substantially) solve the problem where the length of the enrollment window determines the composition of the experiment population. "Write about how they can be applied to all the different contexts" seemed like too-open-ended a task when there was no guarantee about which contexts there was actually going to be work done, in particular work done that could benefit from use of the segments...

Happy to discuss further over slack (or here, if you prefer)

**Comment by tdsmith** [comment]
Okay, thanks. If we develop any new guidance for experimenters we can add it here :)

**Comment by felixlawrence** [comment]
The guidance is _cough_ baked into mozanalysis: you determine people's segments exclusively based on data collected before they enroll in the experiment, to avoid bias from the experiment's treatment making users more/less likely to be measured as being in a given segment.

If we add country-based segments to mozanalysis (probably should!) we might break this rule slightly? Unless we can get the country out of the ping that gave us the enrollment event.

**Comment by tdsmith** [comment]
Sure, but with respect to when and how they should be interested in an analysis of their metrics with respect to any specific segment.

> we might break this rule slightly?

Yeah, I faked something similar here: https://github.com/mozilla/jetstream-config/blob/main/bug-1647305-pref-comcast-steering-experiment-release-78-80.toml#L67-L83

**Comment by felixlawrence** [comment]
Yeah; it may even be worth adjusting our enrollment queries to make this information available as a column in `raw_enrollments` and support a None DataSource...

**Pull request merged**
