### PR TITLE
Add info to guide about creating datasets.

### PR DESCRIPTION
**Pull request by felixlawrence**

### CODE REVIEW

**Comment by tdsmith** [comment]
@benmiroglio Would this have been clearer?

**Comment by benmiroglio** [comment]
I'd just add a note about "this is the space where the analysis below will write tables for future use." BQ's terminology, calling the space a "dataset" is really what made this confusing at first (even being well aware of the terminology!).

**Comment by felixlawrence** [comment]
@benmiroglio Do these changes fix that?

**Comment by benmiroglio** [comment]
@felixlawrence Yes, that is great. Thanks for the quick change!

**Comment by felixlawrence** [comment]
No worries! tdsmith sneakily reassigned you as the reviewer - could you please hit the button so I can merge?

**Pull request merged**
